"""empty message

Revision ID: 9c9bf3a338ad
Revises: a3b8939007a4
Create Date: 2022-08-15 23:49:13.626604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c9bf3a338ad'
down_revision = 'a3b8939007a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('homeworld', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('name', sa.String(length=250), nullable=True))
    op.add_column('character', sa.Column('skill', sa.String(length=250), nullable=False))
    op.drop_column('character', 'character_homeworld')
    op.drop_column('character', 'character_skill')
    op.drop_column('character', 'character_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('character_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('character', sa.Column('character_skill', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('character', sa.Column('character_homeworld', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('character', 'skill')
    op.drop_column('character', 'name')
    op.drop_column('character', 'homeworld')
    # ### end Alembic commands ###
