"""empty message

Revision ID: d4770b7e32ad
Revises: f0d39aa637e2
Create Date: 2022-08-16 00:20:58.206710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4770b7e32ad'
down_revision = 'f0d39aa637e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
