"""empty message

Revision ID: e9fa08758ed0
Revises: 549a0ea1e847
Create Date: 2022-08-16 00:33:30.403698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9fa08758ed0'
down_revision = '549a0ea1e847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_table', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorite_table_ibfk_2', 'favorite_table', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_table', 'planet', ['planet_id'], ['id'])
    op.drop_column('favorite_table', 'planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_table', sa.Column('planet', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorite_table', type_='foreignkey')
    op.create_foreign_key('favorite_table_ibfk_2', 'favorite_table', 'planet', ['planet'], ['id'])
    op.drop_column('favorite_table', 'planet_id')
    # ### end Alembic commands ###
