"""empty message

Revision ID: f0d39aa637e2
Revises: 9c9bf3a338ad
Create Date: 2022-08-16 00:07:25.721944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d39aa637e2'
down_revision = '9c9bf3a338ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('population', sa.Integer(), nullable=False))
    op.add_column('planet', sa.Column('diameter', sa.Integer(), nullable=False))
    op.add_column('planet', sa.Column('climate', sa.String(length=250), nullable=False))
    op.add_column('planet', sa.Column('name', sa.String(length=250), nullable=True))
    op.drop_column('planet', 'planet_climate')
    op.drop_column('planet', 'planet_name')
    op.drop_column('planet', 'planet_population')
    op.drop_column('planet', 'planet_diameter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('planet_diameter', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('planet_population', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('planet_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('planet', sa.Column('planet_climate', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('planet', 'name')
    op.drop_column('planet', 'climate')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'population')
    # ### end Alembic commands ###
